### ISSUE TITLE
Running demo from repo - can't find nativescript files (even successful build)

### ISSUE THREAD

**Issue by evan-williams** [testfairy/nativescript-testfairy#5]
Hi - trying to run the demo app and it falls over on bootstrap:

D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo> tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watch hook from D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.3.4
20:43:46 - Compilation complete. Watching for file changes.

Copying template files...
Platform android successfully added. v3.1.1
Executing before-prepare hook from D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\hooks\before-prepare\nativescript-dev-typescript.js
Preparing project...
Successfully prepared plugin nativescript-testfairy for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-unit-test-runner for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Gradle clean...

 :config phase:  createDefaultIncludeFiles

 :config phase:  addAarDependencies
        +adding dependency: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\libs\aar\testfairy-android-sdk.aar
        +adding dependency: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\libs\aar\widgets-release.aar
Project successfully prepared (Android)
Executing after-prepare hook from D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\hooks\after-prepare\nativescript-unit-test-runner.js
Building project...
Gradle build...

 :config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-testfairy
         + creating include.gradle file for D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\configurations\nativescript-testfairy
Renaming plugin directory to flavor name: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\src\nativescript-testfairy -> D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\src\F0
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\src\tns-core-modules-widgets -> D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\src\F1

 :config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\configurations\include.gradle
        +applying configuration from: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\configurations\nativescript-testfairy\include.gradle
        +applying configuration from: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\configurations\tns-core-modules-widgets\include.gradle

 :config phase:  addAarDependencies
        +adding dependency: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\libs\aar\testfairy-android-sdk.aar
        +adding dependency: D:\Downloads\nativescript-testfairy-master\nativescript-testfairy-master\demo\platforms\android\libs\aar\widgets-release.aar
Running full build
finished with reading lines with js files
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Skip com.testfairy.f.c.a
        Error: java.lang.NullPointerException
Skip com.testfairy.f.c.f
        Error: java.lang.NullPointerException
Project successfully built.
Installing on device 5TCMO7RSZP5SI7CU...
Successfully installed on device with identifier '5TCMO7RSZP5SI7CU'.
Refreshing application on device 5TCMO7RSZP5SI7CU...
Successfully synced application org.nativescript.demo on device 5TCMO7RSZP5SI7CU.
ActivityManager: Start proc 29813:org.nativescript.demo/u0a123 for activity org.nativescript.demo/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-testfairy", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:521)
System.err:     com.tns.Runtime.run(Runtime.java:513)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
System.err:     android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/app.js', line: 4, column: 32
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-testfairy", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:521)
System.err:     com.tns.Runtime.run(Runtime.java:513)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
System.err:     android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/app.js', line: 4, column: 32
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4973)
System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-testfairy", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:521)
System.err:     com.tns.Runtime.run(Runtime.java:513)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
System.err:     android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/app.js', line: 4, column: 32
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-testfairy", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:521)
System.err:     com.tns.Runtime.run(Runtime.java:513)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
System.err:     android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/app.js', line: 4, column: 32
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:521)
System.err:     at com.tns.Runtime.run(Runtime.java:513)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
System.err:     ... 8 more
ActivityManager: Process org.nativescript.demo (pid 29813) has died
ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{448af65 29813:org.nativescript.demo/u0a123}, app.pid = 29813
ActivityManager: cleanUpApplicationRecord -- 29813

**Comment by evan-williams** [comment]
All the node_modules seem to be present, including nativescript-testfairy. So any idea why it can't be found? Can you confirm this demo repo works with latest version of Nativescript (v5)?
